apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud7shisha-db
  name: mongodb-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
  selector:
    app: cloud7shisha-db